# --- IQL specific parameters ---

# Use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 0.0
epsilon_finish: 0.00
epsilon_anneal_time: 1
epsilon_test: 0.0  # Match with training epsilon for evaluation
evaluation_epsilon: 0.0  # Ensures consistency between training and evaluation
runner: "episode"

buffer_size: 5000

# Update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# Use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: True
double_q: True
use_rnn: False
mixer:  # Mixer becomes None

name: "iql"

t_max: 150  # Total timesteps (3 episodes × 50 timesteps/episode)
test_nepisode: 3  # Evaluate over 3 episodes

# Save model every 50 timesteps
save_model: True
save_model_interval: 50